site_name: Учебный проект # Название сайта
site_description: Учебный проект, выполненный в рамках курса «Docs as code для ребят постарше» # Описание сайта, добавляется в meta-теги
theme: # Тема сайта, информация о ее параметрах
  name: material # Название темы
  logo: logo.png # Ссылка на логотип сайта, логотип добавляется в папку `docs/images`
  #font:
  #  text: Roboto # Шрифт текста
  #  code: Roboto Mono # Шрифт для текста кода
  language: ru # Язык
  palette: # Настройки тем
   …
  palette: # Настройки тем
    - scheme: standart
      toggle:
        icon: material/weather-sunny # Иконка для активации светлой темы
        name: Выключить солнышко # Всплывающий текст-подсказка
    # Настройки светлой темы
#    - scheme: default 
#      toggle:
#        icon: material/weather-sunny # Иконка для активации светлой темы
#        name: Выключить солнышко # Всплывающий текст-подсказка
#      primary: custom # Основной цвет
#      accent: blue # Акцентный цвет
    # Настройки тёмной темы
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Позвать солнышко
      primary: custom
      accent: blue
     
  features: # настройки функциональностей темы
   #- navigation.sections # Добавление разделов верхнего уровня в боковом меню, отключение спойлеров в боковом меню
   - navigation.path # Хлебные крошки
   - navigation.indexes # Позволяет создавать корневые страницы разделов меню. Корневая страница должна лежать в папке раздела и называться index.md. Пример использования корневых страниц приведен ниже в настройках nav
   # - navigation.tabs # Верхнее меню
   # - navigation.tabs.sticky # Фиксация верхнего меню
   - navigation.expand # Разворачивает спойлеры в левом меню по умолчанию
   # - toc.integrate # Фиксирует оглавление страницы в левом меню
   - navigation.instant # Функция быстрой загрузки страниц
   - navigation.top # Добавляет кнопку «к началу» для быстрой обратной прокрутки страницы
   - search.suggest # Подсказки при вводе поискового запроса
   - search.highlight # Подсветка результатов поиска в тексте страницы
   - content.code.copy # Кнопка копирования в блоке кода
nav: # Структура сайта
    - Утилита PassportReader. Руководство пользователя:
      - passportreader/index.md
      - Назначение утилиты распознавания удостоверений личности: passportreader/intro.md
      - Требования к версии МИС: passportreader/ver.md
      - Порядок использования утилиты для распознавания документов: passportreader/use.md
      - Установка и настройка утилиты распознавания: 
        - passportreader/setup/index.md
        - Порядок установки программных продуктов, входящих в комплект поставки: passportreader/setup/install.md
        - Настройка параметров работы сканера: passportreader/setup/scaner.md
        - Настройка кнопки вызова утилиты на экранной форме МИС: passportreader/setup/options.md
    - Приложение Нотсарр:
      - notesupp/index.md
      - API документация Swagger: notesupp/api/api-swagger.md
      - API документация Redoc: notesupp/api/api-redoc.md
      - Пользовательский сценарий для приложения Нотсапп: notesupp/notesupp.md

markdown_extensions: # Расширения markdown
  - md_in_html # Поддержка markdown внутри html
  - admonition # Поддержка информационных панелей (сообщений типа «Внимание», «Совет», «Примечание», etc.)
  - footnotes # Поддержка встроенных сносок на страницах
  - attr_list # Использование html-атрибутов и CSS в элементах markdown
  - md_in_html # Поддержка markdown внутри html
  - def_list # Поддержка списков определений
  - pymdownx.tabbed # Использование вкладок (табов)
  - pymdownx.details # Использование спойлеров (катов)
  - pymdownx.highlight: # Подсветка синтаксиса в блоках кода
      anchor_linenums: true
  - pymdownx.superfences # Поддержка вложенных блоков кода
  - pymdownx.snippets # Использование заимствованного контента
  - pymdownx.blocks.html
  - pymdownx.snippets: # Использование заимствованного контента
      base_path:
        - docs
  - pymdownx.emoji: # Иконки и эмодзи
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - glightbox
  - tags:
      tags_allowed:
      - help 
      - manual
  - swagger-ui-tag
  - redoc-tag
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/

copyright: |
  © 2026 All rights reserved by PMT