site_name: Утилита PassportReader. Руководство пользователя # Название сайта
site_description: Учебный проект, выполненный в рамках курса «Docs as code для ребят постарше» # Описание сайта, добавляется в meta-теги
theme: # Тема сайта, информация о ее параметрах
  name: material # Название темы
  logo: images/logo.png # Ссылка на логотип сайта, логотип добавляется в папку `docs/images`
  font:
    text: Roboto # Шрифт текста
    code: Roboto Mono # Шрифт для текста кода
  language: ru # Язык
  palette: # Настройки светлой и тёмной тем
    # Настройки светлой темы
    - scheme: default 
      toggle:
        icon: material/weather-sunny # Иконка для активации светлой темы
        name: Выключить солнышко # Всплывающий текст-подсказка
      primary: blue # Основной цвет
      accent: purple # Акцентный цвет
      # вы можете использовать любой цвет из списка: 
      # red; pink; purple; deep purple; indigo; blue; light blue; cyan; teal; 
      # green; light green; lime; yellow; amber; orange; deep orange; brown; 
      # grey; blue grey; black; white

    # Настройки тёмной темы
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Позвать солнышко
      primary: deep purple
      accent: blue
  features: # настройки функциональностей темы
   #- navigation.sections # Добавление разделов верхнего уровня в боковом меню, отключение спойлеров в боковом меню
   - navigation.path # Хлебные крошки
   - navigation.indexes # Позволяет создавать корневые страницы разделов меню. Корневая страница должна лежать в папке раздела и называться index.md. Пример использования корневых страниц приведен ниже в настройках nav
   # - navigation.tabs # Верхнее меню
   # - navigation.tabs.sticky # Фиксация верхнего меню
   - navigation.expand # Разворачивает спойлеры в левом меню по умолчанию
   # - toc.integrate # Фиксирует оглавление страницы в левом меню
   - navigation.instant # Функция быстрой загрузки страниц
   - navigation.top # Добавляет кнопку «к началу» для быстрой обратной прокрутки страницы
   - search.suggest # Подсказки при вводе поискового запроса
   - search.highlight # Подсветка результатов поиска в тексте страницы
   - content.code.copy # Кнопка копирования в блоке кода
nav: # Структура сайта
    - index.md
    - Назначение утилиты распознавания удостоверений личности: intro.md
    - Требования к версии МИС: ver.md
    - Порядок использования утилиты для распознавания документов: use.md
    - Установка и настройка утилиты распознавания: 
      - setup/index.md
      - Порядок установки программных продуктов, входящих в комплект поставки: setup/install.md
      - Настройка параметров работы сканера: setup/scaner.md
      - Настройка кнопки вызова утилиты на экранной форме МИС: setup/options.md
    - Пользовательский сценарий для приложения Нотсапп: notesupp.md
    - API документация Swagger: api/api-swagger.md
    - API документация Redoc: api/api-redoc.md

markdown_extensions: # Расширения markdown
  - md_in_html # Поддержка markdown внутри html
  - admonition # Поддержка информационных панелей (сообщений типа «Внимание», «Совет», «Примечание», etc.)
  - footnotes # Поддержка встроенных сносок на страницах
  - attr_list # Использование html-атрибутов и CSS в элементах markdown
  - md_in_html # Поддержка markdown внутри html
  - def_list # Поддержка списков определений
  - pymdownx.tabbed # Использование вкладок (табов)
  - pymdownx.details # Использование спойлеров (катов)
  - pymdownx.highlight: # Подсветка синтаксиса в блоках кода
      anchor_linenums: true
  - pymdownx.superfences # Поддержка вложенных блоков кода
  - pymdownx.snippets # Использование заимствованного контента
  - pymdownx.blocks.html
  - pymdownx.emoji: # Иконки и эмодзи
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - glightbox
  - swagger-ui-tag
  - redoc-tag
